#!/usr/bin/env node
/**
 * Regenerate data/links.json from:
 *   - data/links.template.json   (immutable per-segment metadata)
 *   - scripts/links-input.csv    (this run's result_count + mls_url per slug)
 *
 * Sets generated = today (UTC), expires = today + 30 days.
 * Warns about missing slugs in the CSV; errors on extra slugs.
 *
 * Usage:  node scripts/regen-links.js
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const TEMPLATE_PATH = path.join(ROOT, 'data', 'links.template.json');
const OUTPUT_PATH = path.join(ROOT, 'data', 'links.json');
const INPUT_CSV = path.join(__dirname, 'links-input.csv');

function isoDate(d) {
  return d.toISOString().slice(0, 10);
}

function parseCsv(text) {
  const rows = [];
  const lines = text.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith('#')) continue;
    if (i === 0 && /^segment_slug\b/i.test(line)) continue;
    const cols = line.split(',').map((s) => s.trim());
    if (cols.length < 3) {
      console.warn(`[warn] skipping malformed line ${i + 1}: ${raw}`);
      continue;
    }
    const [slug, countStr, mlsUrl] = cols;
    const count = parseInt(countStr, 10);
    if (Number.isNaN(count)) {
      console.warn(`[warn] skipping row with non-integer result_count on line ${i + 1}: ${raw}`);
      continue;
    }
    rows.push({ slug, result_count: count, mls_url: mlsUrl || '' });
  }
  return rows;
}

function main() {
  const template = JSON.parse(fs.readFileSync(TEMPLATE_PATH, 'utf8'));
  const templateSegments = template.segments || {};
  const expectedSlugs = new Set(Object.keys(templateSegments));

  let inputRows = [];
  if (fs.existsSync(INPUT_CSV)) {
    inputRows = parseCsv(fs.readFileSync(INPUT_CSV, 'utf8'));
  } else {
    console.warn(`[warn] No CSV input at ${INPUT_CSV} — emitting empty result_count / mls_url for all segments.`);
  }

  const inputBySlug = new Map();
  let hadError = false;
  for (const row of inputRows) {
    if (!expectedSlugs.has(row.slug)) {
      console.error(`[error] CSV references unknown slug "${row.slug}" — not in data/links.template.json`);
      hadError = true;
      continue;
    }
    if (inputBySlug.has(row.slug)) {
      console.warn(`[warn] duplicate row for slug "${row.slug}" — using last occurrence.`);
    }
    inputBySlug.set(row.slug, row);
  }

  // Warn on missing slugs
  for (const slug of expectedSlugs) {
    if (!inputBySlug.has(slug)) {
      console.warn(`[warn] CSV missing slug "${slug}" — emitting result_count=0, mls_url=''.`);
    }
  }

  if (hadError) {
    process.exitCode = 1;
    console.error('[error] Aborting due to unknown slug(s) above.');
    return;
  }

  const today = new Date();
  const expires = new Date(today.getTime() + 30 * 24 * 60 * 60 * 1000);
  const generated = isoDate(today);
  const expiresStr = isoDate(expires);

  const outSegments = {};
  for (const slug of expectedSlugs) {
    const meta = templateSegments[slug];
    const input = inputBySlug.get(slug) || { result_count: 0, mls_url: '' };
    outSegments[slug] = {
      search_name: meta.search_name,
      label: meta.label,
      result_count: input.result_count,
      mls_url: input.mls_url,
      generated,
      expires: input.mls_url ? expiresStr : '',
      notes: meta.notes,
    };
  }

  const out = {
    last_updated: generated,
    note: 'Regenerated by scripts/regen-links.js. Edit scripts/links-input.csv with the new FlexMLS share links and rerun. Links valid approximately 30 days.',
    segments: outSegments,
  };

  fs.writeFileSync(OUTPUT_PATH, JSON.stringify(out, null, 2) + '\n', 'utf8');
  console.log(`[ok] wrote ${path.relative(ROOT, OUTPUT_PATH)} (generated ${generated}, expires ${expiresStr})`);
  console.log(`[ok] ${Object.keys(outSegments).length} segments processed`);
}

main();
